# Machine Learning Zoomcamp

* 1.8 Linear Algebra Recap
    * Structure:
      * Vector operation
      * Multiplication:
         * Vector - Vector multiplication: Dot Product
         * Matrix - Vector multiplication
         * Materix - Matrix multiplication
      * Identity matrix
      * Inverse   

In [1]:
import numpy as np

## Vector Opeartions

In [2]:
u = np.array([2, 4, 5, 6])

In [3]:
u

array([2, 4, 5, 6])

In [4]:
v = np.array([1, 0, 0, 2])

In [5]:
v

array([1, 0, 0, 2])

In [6]:
u + v

array([3, 4, 5, 8])

In [9]:
u * 2

array([ 4,  8, 10, 12])

## Multiplication

### Vector - Vector Multiplication: Dot Product

In [13]:
def vector_vector_multiplicatio(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [14]:
vector_vector_multiplicatio(u,v)

14.0

In [15]:
# prebuilt function
u.dot(v)

14

## Matrix - Vector Multiplicatoin

In [16]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [17]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [88]:
# my def
def my_matrix_vector_multiplication(u,v):
    assert u.shape[1] == v.shape[0]

    n, m = u.shape[0], u.shape[1]
    
    vector = []
    for i in range(n):
        results = 0.0
        for j in range(m):
            results = results + u[i][j] * v[j]
        vector.append(results)
    return vector

In [89]:
def matrix_vector_multiplication(u,v):
    assert u.shape[1] == v.shape[0]

    num_rows = u.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplicatio(u[i], v)

    return result

In [90]:
my_matrix_vector_multiplication(U, v)

[14.0, 5.0, 5.0]

In [91]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [93]:
# prebuilt function
U.dot(v)

array([14,  5,  5])

## Matrix - Matrix Multiplcations

In [94]:
V = np.array([
    [1,1,2],
    [0, 0.5, 1],
    [0,2,1],
    [2, 1, 0]
])

In [95]:
def matrix_matrix_multiplication(U, v):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [96]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [98]:
# prebuit functions
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Indentity Matrix

In [101]:
np.eye(10) #diagonal is one

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [102]:
I = np.eye(3)

In [103]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [104]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

# Inverse

In [106]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [109]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [110]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])