### Homework

In [30]:
# Q1. Pandas version
import pandas as pd
import numpy as np
pd.__version__

'2.2.3'

In [2]:
# Q2. Records count 
#Data = "wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"
df = pd.read_csv('laptops.csv')
df.shape

(2160, 12)

In [3]:
# Q3. Laptop brands
df.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [4]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.head()

laptop status   brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        model            cpu  ram  storage storage_type       gpu  screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  touch  final_price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [5]:
df.head()

laptop status   brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        model            cpu  ram  storage storage_type       gpu  screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  touch  final_price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [6]:
# Laptop brands
len(df.brand.unique())

27

In [7]:
# Q4. Missing values
df.isnull().sum()

laptop             0
status             0
brand              0
model              0
cpu                0
ram                0
storage            0
storage_type      42
gpu             1371
screen             4
touch              0
final_price        0
dtype: int64

In [8]:
# Q5. What's the maximum final price of Dell notebooks in the dataset?
df[df['brand'] == 'Dell'].final_price.max()

np.float64(3936.0)

In [11]:
# Q6. Find the median value of Screen column in the dataset.
median_screen = df['screen'].median()
median_screen

np.float64(15.6)

In [13]:
# Next, calculate the most frequent value of the same Screen column.
mode_screen = df['screen'].mode()
mode_screen[0]

np.float64(15.6)

In [21]:
# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
df['screen'].fillna(mode_screen[0], inplace=True)

In [24]:
# Now, calculate the median value of Screen once again.
new_median_value = df['screen'].median()
new_median_value

np.float64(15.6)

In [25]:
# Q7. Sum og weights
Innjoo = df[df['brand'] == 'Innjoo']

In [26]:
Innjoo.head()

laptop status   brand model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   

                cpu  ram  storage storage_type  gpu  screen touch  final_price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02

In [28]:
# Select only columns RAM, Storage, Screen.
cols = Innjoo[['ram','storage','screen']]
cols = cols.reset_index(drop=True)
cols

ram  storage  screen
0    8      256    15.6
1    8      512    15.6
2    4       64    14.1
3    6       64    14.1
4    6      128    14.1
5    6      128    14.1

In [48]:
# Get the underlying NumPy array. Let's call it X.
X = cols.values

In [49]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [53]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [55]:
# Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [61]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [62]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = np.dot(np.dot(XTX_inv, X.T), y)

In [66]:
# What's the sum of all the elements of the result?
sum(w)

np.float64(91.2998806299555)