# Machine Learning Zoomcamp

## 1.7 Introduction to Numpy
* Plan: <br>
  * Creating arrays
  * Multi-dimentional arrays
  * Randomly generated arrays
  * Element-wise operations
    * Comparision operations
    * Logical operations
  * Summarizing operations

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/rasul/anaconda3/envs/ml-zoomcamp/lib/python3.9/site-packages/numpy/__init__.py'>

## Creating arrays

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1, 2, 6, 7, 8])
a

array([1, 2, 6, 7, 8])

In [10]:
a[2] #accessing element

6

In [11]:
a[3] = 10 #assigning values

In [12]:
a

array([ 1,  2,  6, 10,  8])

In [15]:
np.arange(10) #not 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimentional arrays

In [20]:
np.zeros((5,2)) #5x2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# accessing element
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

matrix[0][1] # row 0, column 1

2

In [25]:
matrix[1] # accessing the row

array([4, 5, 6])

In [28]:
matrix[:,2] # accessing the column

array([3, 6, 9])

In [29]:
# assigning values
matrix[2] = [11, 14, 15]

In [30]:
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 14, 15]])

## Randomly generated arrays

In [38]:
np.random.seed(2) # to get result reproducible
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [39]:
np.random.seed(2)
np.random.randn(5, 2) #random normal

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [40]:
np.random.seed(2)
np.random.randint(low=0,  high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [41]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [44]:
# a + 1
# a * 2
# a / 100
# 100 * a

In [45]:
b = (10 + (a * 2)) ** 2 / 100

In [46]:
a

array([0, 1, 2, 3, 4])

In [47]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

## Comparison operations

In [48]:
a 

array([0, 1, 2, 3, 4])

In [49]:
a >= 2

array([False, False,  True,  True,  True])

In [50]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [51]:
a > b

array([False, False,  True,  True,  True])

In [53]:
a[a > b] # return which conditions are true

array([2, 3, 4])

## Summarizing operations

In [55]:
a.min() # smallest num

0

In [56]:
a.max() # maximum num

4

In [57]:
a.sum() # total sum

10

In [61]:
a.std() # standard deviation

1.4142135623730951

In [60]:
len(a)

5